# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: CopyFiles@1
  displayName: 'Copy Files to: $(Build.BinariesDirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\*.exe'
    TargetFolder: '$(Build.BinariesDirectory)'
    CleanTargetFolder: true
    OverWrite: true
    flattenFolders: true

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.BinariesDirectory)'
  inputs:
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/release.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: release'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: release
